ALTER TABLE [dbo].[System_Parameters]
    ADD CONSTRAINT [IX_System_Parameters] UNIQUE NONCLUSTERED ([ParameterName] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

