ALTER TABLE [dbo].[LookupUserType]
    ADD CONSTRAINT [PK_LookupUserType] PRIMARY KEY CLUSTERED ([LookupUserTypeID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

