ALTER TABLE [dbo].[LookupQuestionType]
    ADD CONSTRAINT [PK_LookupQuestionType] PRIMARY KEY CLUSTERED ([LookupQuestionTypeID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

