ALTER TABLE [dbo].[RecruitmentTestQuestions]
    ADD CONSTRAINT [PK_Question] PRIMARY KEY CLUSTERED ([RecruitmentTestQuestionsID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

