ALTER TABLE [dbo].[RecruitmentTestRights_Details]
    ADD CONSTRAINT [PK_RecruitmentTestRights_Details] PRIMARY KEY CLUSTERED ([RecruitmentTestRights_DetailsID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

