ALTER TABLE [dbo].[RecruitmentTestApplicant]
    ADD CONSTRAINT [PK_RecruitmentTestApplicant] PRIMARY KEY CLUSTERED ([RecruitmentTestApplicantID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

