ALTER TABLE [dbo].[RecruitmentTestExams_Questions]
    ADD CONSTRAINT [PK_RecruitmentTestExams_Questions] PRIMARY KEY CLUSTERED ([RecruitmentTestExams_QuestionsID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

