ALTER TABLE [dbo].[RecruitmentTestRights]
    ADD CONSTRAINT [PK_RecruitmentTestRights] PRIMARY KEY CLUSTERED ([RecruitmentTestRightsID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

