ALTER TABLE [dbo].[RecruitmentTestExams_Answers]
    ADD CONSTRAINT [PK_RecruitmentTestExams_Answers] PRIMARY KEY CLUSTERED ([RecruitmentTestExams_AnswersID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

