ALTER TABLE [dbo].[System_Modules_AccessLib]
    ADD CONSTRAINT [PK_System_Modules_AccessLib] PRIMARY KEY CLUSTERED ([System_Modules_AccessLibID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

