ALTER TABLE [dbo].[System_BindDefinition]
    ADD CONSTRAINT [PK_System_BindDefinition] PRIMARY KEY CLUSTERED ([System_BindDefinitionID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

