ALTER TABLE [dbo].[System_BindDefinition_Field]
    ADD CONSTRAINT [PK_System_BindDefinition_Field] PRIMARY KEY CLUSTERED ([System_BindDefinition_FieldID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

