ALTER TABLE [dbo].[System_Lookup]
    ADD CONSTRAINT [PK_System_Lookup] PRIMARY KEY CLUSTERED ([System_LookupID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

