ALTER TABLE [dbo].[System_Modules_Access]
    ADD CONSTRAINT [PK_System_Modules_Access] PRIMARY KEY CLUSTERED ([System_Modules_AccessID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

